---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: keycloak
  namespace: auth
spec:
  interval: 24h
  url: oci://registry-1.docker.io/bitnamicharts/keycloak
  ref:
    tag: 24.4.9
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keycloak
  namespace: auth
spec:
  chartRef:
    kind: OCIRepository
    name: keycloak
    namespace: auth
  interval: 30m
  values:
    ingress:
      enabled: true
      ingressClassName: traefik
      hostname: cloudlabs-keycloak.duckdns.org
      annotations:
        kubernetes.io/ingress.class: traefik
        cert-manager.io/cluster-issuer: letsencrypt
      tls: true
