---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: keycloak
  namespace: auth
spec:
  interval: 24h
  url: oci://registry-1.docker.io/bitnamicharts/keycloak
  ref:
    tag: 24.7.1
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keycloak
  namespace: auth
spec:
  chartRef:
    kind: OCIRepository
    name: keycloak
    namespace: auth
  interval: 30m
  values:
    ingress:
      enabled: true
      ingressClassName: traefik
      hostname: cloudlabs-keycloak.duckdns.org
      annotations:
        kubernetes.io/ingress.class: traefik
        cert-manager.io/cluster-issuer: letsencrypt
      tls: true
    extraEnvVars:
      - name: KC_SPI_EVENTS_LISTENER_OPENFGA_EVENTS_PUBLISHER_OPENFGA_API_URL
        value: http://openfga.auth:8080
      - name: KC_SPI_EVENTS_LISTENER_OPENFGA_EVENTS_PUBLISHER_OPENFGA_API_TOKEN
        valueFrom:
          secretKeyRef:
            name: preshared-keys
            key: keys
    initdbScripts:
      10_openfga_event_publisher.sh: |
        #!/bin/bash
        set -euo pipefail
        echo "[initdb] Installing OpenFGA provider"
        curl -sSL \
          https://github.com/cloudlabs-ufscar/keycloak-openfga-event-publisher/releases/download/1.2.3/keycloak-openfga-event-publisher.jar \
          -o /opt/bitnami/keycloak/providers/keycloak-openfga-event-publisher.jar
        ls -l /opt/bitnami/keycloak/providers
    resources:
      requests:
        cpu: 0.75
        memory: 512Mi
      limits:
        cpu: 2
        memory: 2Gi
    proxy: edge
