---
apiVersion: v1
kind: Namespace
metadata:
  name: loadbalance
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: metallb
  namespace: loadbalance
spec:
  interval: 24h
  url: https://metallb.github.io/metallb
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metallb
  namespace: loadbalance
spec:
  interval: 30m
  chart:
    spec:
      chart: metallb
      version: ">=0.14.0"
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: loadbalance
      interval: 12h
  install:
    crds: Create
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
